apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: eso-test-app
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: conjur-secret-store
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  data:
    - secretKey: username
      remoteRef:
        key: secrets/username
    - secretKey: password
      remoteRef:
        key: secrets/password
